Vidly/Vidly/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vidly.DTOs;
using Vidly.Models;
using HttpGetAttribute = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;

namespace Vidly.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MoviesController : ControllerBase
    {
        DBModel _context;
        public MoviesController(DBModel context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult GetMovies(string query)
        {
            
            IQueryable<Movie> list = _context.Movies;
            if (query != null)
                list = _context.Movies.Where(c => c.Name.Contains(query) && c.NumberAvailable > 0);

            var movies =list.Select(c => new MovieDto() { Id = c.Id, Name = c.Name, ReleaseDate = c.ReleaseDate, GenreId = c.GenreId, NumberInStock = c.NumberInStock,Genre=c.Genre });

            return Ok(movies);
        }

        [HttpGet("{id}")]
        public IActionResult GetMovie(int id)
        {
            var movie =_context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
                return NotFound();
            MovieDto dto = new MovieDto(movie);
            return Ok(dto);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IActionResult CreateMovie(MovieDto mov)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            var movie = new Movie() { Id = mov.Id, Name = mov.Name, ReleaseDate = mov.ReleaseDate, GenreId = mov.GenreId, NumberInStock = mov.NumberInStock };
            _context.Movies.Add(movie);
            _context.SaveChanges();

            return Created(new Uri(Request.GetDisplayUrl()+"/"+movie.Id),movie);
        }

        [Microsoft.AspNetCore.Mvc.HttpPut]
        public IActionResult UpdateMovie(int md,MovieDto mov)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == md);
            if (movie == null)
            {
                return NotFound();
            }
            movie.Name = mov.Name;
            movie.NumberInStock = mov.NumberInStock;
            movie.GenreId = mov.GenreId;
            movie.ReleaseDate = mov.ReleaseDate;
            _context.SaveChanges();

            return Ok();
        }
        [HttpDelete("{id}")]
        public IActionResult DeleteMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
            {
                return NotFound();
            }
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            
            return Ok();
        }
    }
}

Vidly/Vidly/Controllers/NewRentalsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vidly.Filters;

namespace Vidly.Controllers
{
    public class NewRentalsController : Controller
    {
        [Authenticate]
        public IActionResult New()
        {
            return View("New");
        }
    }
}

Vidly/Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/toastr/2.1.1/content/content/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        @*Html.Partial("_NavBar")*@
        <partial name="_NavBar">
           
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vidly - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/DataTables/jquery.dataTables.js"></script>
    <script src="~/lib/DataTables/dataTables.bootstrap4.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/toastr/2.1.1/content/scripts/toastr.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vidly/Vidly/Views/Shared/_NavBar.cshtml
@using System.Text.Json;
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    byte[] data;
    Html.ViewContext.HttpContext.Session.TryGetValue("UserId", out data);
    Users user =null;
    if (data != null)
    {
        int id = JsonSerializer.Deserialize<int>(data);
        var db = (DBModel)Html.ViewContext.HttpContext.RequestServices.GetService(typeof(DBModel));
        user = db.Users.FirstOrDefault(c => c.Id == id);

    }
}
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Vidly</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="NewRentals" asp-action="New">New Rentals</a>
                </li>
                @if (user == null)
                {
                    <li class="nav-item ml-auto">
                        <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                }
                else
                {
                    <li class="nav-item ml-auto">
                        <span class="nav-link text-white">Hello @user.Name</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="LogOut">Log Out</a>
                    </li>
                }

            </ul>
        </div>
    </div>
</nav>